source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'
gem 'sqlite3'

group :assets do
  gem 'sass-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.0.0'
end

gem 'taglib-ruby', '~> 0.6.0'
gem 'faraday', '~> 0.9.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'

#Reading tags
#gem 'taglib-ruby', '~> 0.6.0'

group :test, :development do
  gem 'rspec-rails', '~> 2.14.1'
  gem 'database_cleaner', '1.2.0'
end

group :test do
  gem 'capybara', '2.2.1'
  gem 'factory_girl_rails', '4.3.0'
  gem 'factory_girl', '4.3.0'
end


group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
